[tool.poetry]
name = "find-apartments"
version = "0.1.0"
description = ""
authors = ["bythewaters <bythewaters800@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
